# Секция 'run' настраивает общие параметры выполнения линтера.
run:
  # Установим таймаут для выполнения. Увеличьте, если проект большой.
  timeout: 5m
  # Количество файлов, проверяемых одновременно.
  # Можно настроить для оптимизации производительности.
  concurrency: 4

---
# Секция 'linters-settings' настраивает параметры для отдельных линтеров.
linters-settings:
  # Настройки линтера 'lll' (line length).
  lll:
    line-length: 120
    tab-width: 4
  # Настройки линтера 'funlen' (function length).
  funlen:
    lines: 60
    statements: 40
  # Настройки линтера 'goimports'.
  # Замените 'github.com/your-username/your-project' на ваш префикс.
  goimports:
    local-prefixes: github.com/your-username/your-project
  # Настройки линтера 'gocyclo' (cyclomatic complexity).
  gocyclo:
    min-complexity: 15

---
# Секция 'linters' управляет, какие линтеры включены или выключены.
linters:
  # Мы включаем все линтеры, которые наиболее полезны для современного Go-кода.
  enable:
    - gofmt
    - goimports
    - gosec
    - staticcheck
    - unparam
    - nolintlint
    - errcheck
    - lll
    - funlen
    - gocritic
    - gosimple
    - unused
    - whitespace
    - gocyclo
    - dupl
    - nakedret
    - dogsled
    - sqlclosecheck # Проверяет, что SQL-соединения и строки закрываются.

  # Мы выключаем линтеры, которые часто бывают излишне строгими
  # или функционал которых уже включён в 'staticcheck'.
  disable:
    - scopelint # Устарел, используйте 'gocritic'.
    - deadcode # Устарел, его функционал есть в 'staticcheck'.
    - structcheck # Устарел, его функционал есть в 'staticcheck'.

---
# Секция 'issues' настраивает, как и где отображать ошибки.
issues:
  # Правила для игнорирования определённых ошибок.
  exclude-rules:
    # Игнорировать ошибки в автоматически сгенерированных файлах.
    - text: "autogenerated file"
      source: "github.com/golangci/golangci-lint"
      path: ".*_gen.go"
    # Игнорировать дублирующийся код, если он очень короткий.
    - linters:
        - dupl
      text: "duplicate of "
      source: "github.com/golangci/golangci-lint"

# Секция для исключения директорий из проверки.
exclude-dirs:
  - vendor
  - tests