log:
  level: "info"
  format: "json"

sources:
  - name: "test.ru"
    url: "test.ru/food"
    timeout: 10s
    product_per_page: 80
    request_delay: 2000

db:
  name: "postgres"
  batch_size: 1000
