log:
  level: "info"
  format: "json"

sources:
  - name: "test.ru"
    url: "test.ru/food"
    timeout: 10000
    product_per_page: 80
    request_delay: 2000

db:
  name: "postgres"
  dsn: "postgres://postgres:@localhost:5432/postgres?sslmode=disable"
  batch_size: 1000
